### ISSUE TITLE
Provide an option to retry forever on 503 and 504 responses

### ISSUE THREAD

**Issue by leviroth** [praw-dev/prawcore#78] opened 2019-05-26 14:15 UTC
The vast majority of exceptions that prawcore raises to my bot are 503 and 504 status codes when Reddit is experiencing outages. In this case, the only sensible thing to do is to wait a while and try again.

I think it would make sense for prawcore to provide this behavior as an option, rather than re-implementing it in every client that wants this behavior.

It probably should be optional, so that (e.g.) applications with user interfaces can just report the outage instead of stalling indefinitely.

Does it sound right for prawcore to do this?

**Comment by bboe** [comment] 2019-05-26 15:49
Yes, I think that makes sense for prawcore to have support to do that.

**Comment by Watchful1** [comment] 2020-05-01 23:20
Just to leave an anecdote, I have experienced issues in the past where the reddit api returns a 5XX error, but also completes the action you requested. I usually have a very long wait period before retrying 5XX errors so I don't accidentally post hundreds of duplicate comments during an outage.

It might be worth leaving a warning about that in the documentation for this setting.

**Comment by leviroth** [comment] 2020-05-02 12:22
That's unfortunate, to the point where this whole project starts to sound like a bad idea.

**Comment by Watchful1** [comment] 2020-05-02 17:06
It's definitely a rare edge case, most of the time it doesn't complete the action.

**Comment by dequeued0** [comment] 2020-06-01 04:56
Doing infinite retry with certain API calls that can be repeated and generate an effect each time they are repeated seems dubious to me. Off the top of my head (so a few of these may not be true, and I am almost positive I am missing some too): submitting, commenting, sending messages, giving awards, sending modmail, archiving modmail, and adding a private moderator note to a modmail thread.

**Comment by PythonCoderAS** [comment] 2020-06-01 11:37
Maybe methods that do some kind of retry should perform checks every subset of retries by fetching data and seeing if the request went through.

**Comment by dequeued0** [comment] 2020-06-01 17:55
> Maybe methods that do some kind of retry should perform checks every subset of retries by fetching data and seeing if the request went through.

The problem is that you can't tell if the request went through without a reference to the result. You'd could try to make some sort of API-specific guess, but it's going to take multiple API calls in many cases, and this application logic is far beyond what **prawcore** should be doing.

Since this request is focused on non-interactive Reddit clients such as bots, I think it's generally far better to add some generalized code to handle "the site is dead or nearly dead" case to each application because different applications have different needs for this use case. Also, many applications need much more specific error handling code for higher risk parts of the code.

If this really needs to be part of praw or prawcore, my suggestion would be to adopt a different approach. This should still be optional, of course.

- If prawcore has N consecutive 503 or 504 errors, call a common "retry until Reddit is better" helper. By default, this could even just be 2 or 3 errors.
- The retry until Reddit is better helper would make a single 100% harmless and safe API call (e.g., `GET /api/v1/me`). If that fails, sleep 60 seconds and then try again (perhaps make this delay configurable). Repeat *that* forever. If/when that succeeds, exit the helper, return an exception to the original call, and allow the client to proceed.
- Consider having this helper log some at the warning level in a way that wouldn't be too spammy. Maybe on entrance, on exit, and on every M retries in between. I suppose logging once a minute would be fine.
- If a different error is returned, perhaps a different exception could be returned rather than continuing to fail. In other words, it should only loop forever for 503 and 504 errors.
- I'd *consider* also incorporating 500 and 502 errors into this issue.

**Comment by PythonCoderAS** [comment] 2020-06-01 19:08
@dequeued0 Not sure on 500 errors. I know for example that malformed API calls to the GraphQL system for example returns 500 errors instead of 400 errors.

**Comment by leviroth** [comment] 2020-06-04 00:11
@dequeued0 I really like this suggestion.

Re: the choice of which errors to handle, is the thought that other server errors are less likely to be transient?

**Comment by dequeued0** [comment] 2020-06-04 09:16
I picked those errors based on transient errors that I've seen in my logs.

I think it's generally best to include exception handling and retry logic in your own application code. It doesn't end up being that complicated for most bots.

**Comment by bboe** [comment] 2021-06-05 16:41
This issue has been open for a long time. How are people feeling about it?

**Comment by MaybeNetwork** [comment] 2021-06-06 02:45
I know of at least one endpoint that returns 503s as the primary mode of failure when one of the values in the request payload is incorrect.

    reddit=praw.Reddit()
    reddit.request("POST","api/v1/subreddit/test_welcome_message", data={"sr":"", "message": "message"})

returns a 503 with a response body of

    {'message': 'Service Unavailable', 'error': 503}

This happens when `sr` is any invalid sub name, `sr` is left out, or if `data` is left out entirely.

Test_welcome_message is not yet in PRAW, but it's on my list of things to add. It's an unlisted oauth endpoint used by new Reddit, so perhaps they expect any failure to be their own fault.

500s and 502s are also easy to trigger.

**Comment by bboe** [comment] 2021-06-07 22:23
After briefly looking at this, an "infinite" retry is essentially doable by using a FiniteRetryStrategy with a very large retry number. Unfortunately, the Session initializer does not currently allow the strategy class nor its arguments to be passed in. It seems like exposing that to the session is the first step. If PRAW is to leverage this change, then we need a way to pass settings through the `session` helper function.

**Comment by bboe** [comment] 2021-06-11 03:13
I'm going to close this issue. If someone has a strong desire for such a feature we can create a new one.

**Closed by bboe** 2021-06-11 03:13 UTC
